### ISSUE TITLE
Fixed book image size

### ISSUE THREAD

**Issue by kennethlarsen** [2016rshah/bookshelf#5]
The book covers have different sizes when displaying in 'Your Bookshelf'. This looks messy.

**Comment by 2016rshah** [comment]
Sorry for taking so long for getting back to you on this, I apologize

You're right, the book covers have different sizes, but I think that's actually alright. If you think about a real life bookshelf, books come in all different shapes and sizes, which might be part of their allure. So I'm not too worried about the different sizes. Also, I don't like the idea of defining a fixed-width for books in terms of px because one size won't fit all screen-sizes

Again, I'm so sorry about not being quicker to get back to you, but I really do appreciate your work
